// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tmktwsinbyoqxgmkqcjh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRta3R3c2luYnlvcXhnbWtxY2poIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxODA1MjMsImV4cCI6MjA2ODc1NjUyM30.TQFIuv0WEbIlByH1mJdhRYFbuy79ZAAm_LPFkxnyWyU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});